# Generated by Django 2.1.3 on 2018-11-30 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
        ),
    ]
