# Generated by Django 2.1.3 on 2018-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20181130_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
